default: &default
  adapter: sqlite3
  encoding: unicode

development:
  <<: *default
  database: dummy_development

test:
  <<: *default
  database: dummy_test

production:
  <<: *default
  database: dummy_development
